PR Luis Garcia Garces
UNIZAR-30246-WebEngineering/lab1-git-race pull request #14
Opened 2020-09-19 20:11 UTC by luisgg98

The new feature allow users to access to /rings-quote and visualize a quote from one of the films of the Lord of the Rings.

2020-09-20 15:25 UTC, fjlopez requested changes

2020-09-20 15:25 UTC, fjlopez commented on src/main/java/es/unizar/webeng/hello/RingsQuote.java
> +                .header("Authorization", "Bearer COd1dmY6BQA2Pujr05Bv")
Keys must not be shared in GitHub. Replace it by a value that it is stored in `application.properties` (but not set in your next commit) and explain in the documentation how people that clone locally this repo can obtain this API key and configure the application.

2020-09-21 08:50 UTC, luisgg98 commented
I think it's done. Please, check it out.

2020-09-21 10:32 UTC, fjlopez approved these changes

2020-09-21 10:49 UTC, merged

2020-09-22 15:09 UTC, luisgg98 commented
I added a Kubernetes deployment on local for the application