New functionality added, new number system converter.
UNIZAR-30246-WebEngineering/lab1-git-race pull request #18
Opened 2020-09-22 18:07 UTC by 764429

2020-09-24 15:15 UTC, fjlopez requested changes
I have removed JSP files (not supported anymore). If you want to get a :gift: you must fix your BaseConverterUnitTest. The test is not a @WebMvcTest. It is a plain parametized unit test. A @WebMvcTest simulate a HTTP request and checks the response. See examples such as https://reflectoring.io/spring-boot-web-controller-test/

2020-09-24 16:59 UTC, 764429 commented
I have fixed the problem, please check it out.

2020-09-25 08:03 UTC, fjlopez approved these changes

2020-09-25 08:07 UTC, fjlopez commented
I will merge the PR, but this is not the requested test improvement. If you improve this or other test using [MocMvc](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/web/servlet/MockMvc.html) in a future PR (especially if you keeps your initial parametrised approach - I requested to improve it in the web test, not to remove the parametrisation of the test), I will grant you the :gift:.

2020-09-25 08:08 UTC, merged