Docker & Docker compose
UNIZAR-30246-WebEngineering/lab1-git-race pull request #3
Opened 2022-09-16 18:38 UTC by hec7orci7o

## Use Docker to run the app
creation of a dockerfile that can be found in: `src/main/docker/app.dockerfile`
explanation can be found in `description.md` under the title of *`Docker Usage`*

## Use Docker Compose to run the app
creation of a docker-compose.yml that can be found in the `root directory`
explanation can be found in `description.md` under the title of *`Docker-compose`*

2022-09-17 18:04 UTC, fjlopez commented
You have been awarded a :gift: for your contribution. However, you need to fix the minor issues found.

2022-09-17 18:36 UTC, hec7orci7o reviewed
I can't find the bugs you are talking about, do you mean checking the changes to be able to do the merge, if so, the only thing that is different is the readme which as you said I have added my status badge.

2022-09-17 20:29 UTC, fjlopez commented
Do you cannot see the reviews?

2022-09-17 20:32 UTC, fjlopez commented
Sorry, the reviews were unfinished. Now they are visible.

2022-09-18 10:12 UTC, hec7orci7o commented on README.md
> +[Hec7or-Uni](https://github.com/Hec7or-Uni/lab1-git-race) |798095 | [![Build Status](https://github.com/Hec7or-Uni/lab1-git-race/actions/workflows/ci.yml/badge.svg)](https://github.com/Hec7or-Uni/lab
only 1?

2022-09-18 10:14 UTC, fjlopez commented on README.md
> +[Hec7or-Uni](https://github.com/Hec7or-Uni/lab1-git-race) |798095 | [![Build Status](https://github.com/Hec7or-Uni/lab1-git-race/actions/workflows/ci.yml/badge.svg)](https://github.com/Hec7or-Uni/lab
Yep, only 1 per lab.

2022-09-18 10:15 UTC, hec7orci7o commented on README.md
> +[Hec7or-Uni](https://github.com/Hec7or-Uni/lab1-git-race) |798095 | [![Build Status](https://github.com/Hec7or-Uni/lab1-git-race/actions/workflows/ci.yml/badge.svg)](https://github.com/Hec7or-Uni/lab
Moby Dick: Use Docker to run the app
Moby Dick II: Use Docker Compose to run the app,

I feel ripped off, that was not announced.

2022-09-18 10:17 UTC, fjlopez requested changes

2022-09-18 10:17 UTC, fjlopez commented on description.md
> +```sh=
Remove the `=` and add an empty line before

2022-09-18 10:17 UTC, fjlopez commented on description.md
> +```
Remember, add the language and add an empty line before all the code blocks

2022-09-18 10:18 UTC, hec7orci7o reviewed
now should be fine

2022-09-18 10:21 UTC, fjlopez commented on README.md
> +[Hec7or-Uni](https://github.com/Hec7or-Uni/lab1-git-race) |798095 | [![Build Status](https://github.com/Hec7or-Uni/lab1-git-race/actions/workflows/ci.yml/badge.svg)](https://github.com/Hec7or-Uni/lab
Check the slides in moodle on "¿Como premiar el trabajo individual?" and also in the GUIDE.md

![image](https://user-images.githubusercontent.com/3294927/190897302-7c857c4e-c8ca-40e1-9bbd-96d47fed9763.png)

2022-09-18 10:41 UTC, hec7orci7o reviewed
updated files that differ locally to avoid merge conflicts

2022-09-18 14:34 UTC, fjlopez approved these changes

2022-09-18 14:47 UTC, merged