new
UNIZAR-30246-WebEngineering/lab1-git-race pull request #30
Opened 2023-03-14 21:19 UTC by 890464

2023-03-16 10:16 UTC, fjlopez requested changes
You should fix first these minor problems. Do not close this PR, just push your changes to GitHub and the PR will automatically be modified. Send me an email when it is done.

2023-03-16 10:16 UTC, fjlopez commented on src/main/kotlin/MyController/END.kt
Changes required:
- [ ] rename `MyController` to `mycontroller` (lowercase for folders and packages, best practice)
- [ ] rename `END.kt` to `MyController.kt` (same name as main class in file, best practice)
- [ ] add `package mycontroller` at the beginning of the file (name of the folder, best practice)

2023-03-17 08:05 UTC, 890464 commented on src/main/kotlin/MyController/END.kt
i fix them

2023-03-17 08:08 UTC, 890464 commented
i fix them

2023-03-17 08:36 UTC, fjlopez requested changes
Review both comments

2023-03-17 08:36 UTC, fjlopez commented on src/main/kotlin/mycontroller/MyController.kt
> +import java.awt.image.Raster
Why this import is needed?

2023-03-17 08:36 UTC, fjlopez commented on src/main/kotlin/mycontroller/MyController.kt
> +            /**
Does this comment is ok?

2023-03-17 08:46 UTC, 890464 commented on src/main/kotlin/mycontroller/MyController.kt
> +import java.awt.image.Raster
add package mycontroller at the beginning of the file (name of the folder, best practice)
because of what you worte, i thought i should write like this. what should to do now ?

2023-03-17 08:48 UTC, fjlopez commented on src/main/kotlin/mycontroller/MyController.kt
> +import java.awt.image.Raster
The comment is about `import java.awt.image.Raster`

2023-03-17 08:55 UTC, 890464 commented on src/main/kotlin/MyController/END.kt
i remove #import java.awt.image.Raster

2023-03-17 08:57 UTC, 890464 commented on src/main/kotlin/mycontroller/MyController.kt
> +            /**
should i change it or add something  ??

2023-03-17 08:58 UTC, fjlopez commented on src/main/kotlin/mycontroller/MyController.kt
> +            /**
Does the comment reflect the behavior of the method?

2023-03-17 09:02 UTC, 890464 commented on src/main/kotlin/mycontroller/MyController.kt
> +            /**
im really confused , 
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RestController

@RestController
class MyController {

    @GetMapping("/hello")
    fun hello(): String {
        return "Hello, World!"
    }
}

2023-03-17 09:10 UTC, 890464 commented on src/main/kotlin/mycontroller/MyController.kt
> +            /**
can i add

 fun main() {
    val num1 = 10
    val num2 = 10
    val sum = num1 + num2
    println("The sum of $num1 and $num2 is $sum")
}

2023-03-17 09:10 UTC, fjlopez commented on src/main/kotlin/mycontroller/MyController.kt
> +            /**
Do this short online introduction course to Kotlin. 
https://play.kotlinlang.org/byExample/overview

2023-03-17 09:23 UTC, 890464 commented on src/main/kotlin/mycontroller/MyController.kt
> +            /**
professor your told me that you can add any code in exercise 1.
what is my problem ?

2023-03-19 16:43 UTC, fjlopez commented on src/main/kotlin/mycontroller/MyController.kt
> +            /**
Any working code.

2023-03-19 16:44 UTC, fjlopez commented on src/main/kotlin/MyController/END.kt
Next time, click as I did in the GitHub interface to mark the finished tasks. 
<img width="139" alt="image" src="https://user-images.githubusercontent.com/3294927/226191445-98fb2f9f-6802-4db2-80e6-e7f5511caa89.png">

2023-03-19 16:47 UTC, merged

2023-03-19 16:47 UTC, fjlopez commented
Confirmed. I will also close #29