coronavirus API
UNIZAR-30246-WebEngineering/lab1-git-race pull request #31
Opened 2020-10-20 10:26 UTC by cul3bro

This pull request adds the functionality of the coronavirus API

2020-10-20 21:19 UTC, fjlopez requested changes
Some key changes are requested. They are related to a better use of the Spring Technology and Java features.

2020-10-20 21:19 UTC, fjlopez commented on src/main/java/es/unizar/webeng/hello/coronaAPI.java
> +public class coronaAPI {
This class should be named `CoronaAPI` and  annotated as a @Service and injected into the HelloController. A public method named e.g.  `coronaAPI` should return an `Optional<CoronaDTO>`. This optional must be returned empty if any exception is detected.

2020-10-20 21:19 UTC, fjlopez commented on src/main/java/es/unizar/webeng/hello/HelloController.java
> +        coronaAPI corona = new coronaAPI();
This should be a call to an injected service. The return must be an `Optional<CoronaDTO>`. The semantics of `Optional` allows a solution similar to the current but standard.

2020-10-22 19:29 UTC, cul3bro commented on src/main/java/es/unizar/webeng/hello/HelloController.java
> +        coronaAPI corona = new coronaAPI();
I can't implement the changes you mention ...

2020-10-22 19:29 UTC, cul3bro commented on src/main/java/es/unizar/webeng/hello/coronaAPI.java
> +public class coronaAPI {
I can't implement the changes you mention ...

2020-10-23 15:26 UTC, fjlopez approved these changes

2020-10-23 15:26 UTC, merged