Travis-CI Daniel Barcelo
UNIZAR-30246-WebEngineering/lab1-git-race pull request #32
Opened 2020-10-20 12:16 UTC by DaniBarcelo

2020-10-20 21:24 UTC, fjlopez commented
I assume that this PR is a work in progress. It is not finished yet, isn't?

2020-10-22 14:39 UTC, fjlopez requested changes
Just check my fix and tell me if it worked ASAP

2020-10-22 14:39 UTC, fjlopez commented on src/main/java/es/unizar/webeng/hello/RockPaperScizorsController.java
> +    static class ValueDTO {
I have fixed this that looked very weird! IMHO it should work now. Test it and confirm it works!

2020-10-22 18:55 UTC, DaniBarcelo commented on src/main/java/es/unizar/webeng/hello/RockPaperScizorsController.java
> +    static class ValueDTO {
It didn't work because the function that the test uses was deleted. I kept your decision of changing the place where the class"ValueDTO" was located, but I kept the function that was needed by the tests. If not, the code won't work and the Travis CI resulted in a failure

2020-10-22 18:56 UTC, DaniBarcelo commented
It should work now, everything is ready to be merged with the main repository

2020-10-23 15:24 UTC, fjlopez approved these changes

2020-10-23 15:24 UTC, merged