Added code explanation to welcome.html
UNIZAR-30246-WebEngineering/lab1-git-race pull request #6
Opened 2022-09-17 11:02 UTC by HugoLazaro

2022-09-17 20:34 UTC, fjlopez requested changes

2022-09-17 20:34 UTC, fjlopez commented on README.md
> +(https://travis-ci.org/HugoLazaro/lab1-git-race)
Remove this line

2022-09-17 20:35 UTC, fjlopez commented
Remove the line and leave an empty line. Next, I will accept your PR.

2022-09-18 09:02 UTC, HugoLazaro commented on README.md
> +(https://travis-ci.org/HugoLazaro/lab1-git-race)
I have removed the last line

2022-09-18 09:42 UTC, fjlopez commented
My comment in the review was not very accurate. Remove line 18 (it is useless because your data is in line 17) and replace it with an empty line. Ending text documents with an empty line is a good practice.

2022-09-18 10:49 UTC, HugoLazaro commented on README.md
> +(https://travis-ci.org/HugoLazaro/lab1-git-race)
Is this correct now? I have replaced line 18 with an empty line.

2022-09-18 14:50 UTC, merged