Initial steps + first documentation HectorG
UNIZAR-30246-WebEngineering/lab1-git-race pull request #7
Opened 2022-09-17 11:34 UTC by HectorRute98

2022-09-17 11:36 UTC, HectorRute98 commented
Add documentation to HelloController.kt and HelloControllerUnitTest.kt

2022-09-17 20:37 UTC, fjlopez requested changes

2022-09-17 20:37 UTC, fjlopez commented on src/main/kotlin/controller/HelloController.kt
> +/* This class HelloController.kt creates a variable of type map and implements a function
Check the example at https://kotlinlang.org/docs/kotlin-doc.html and format the documentation according to the best practices.

2022-09-17 20:37 UTC, fjlopez commented on src/test/kotlin/controller/HelloControllerUnitTests.kt
> +/*  Unit test for the class LAB1-GIT-RACE/src/main/kotlin/controller/HelloController.kt
Same.

2022-09-17 20:37 UTC, fjlopez commented on src/test/kotlin/controller/HelloControllerUnitTests.kt
> +    /* Unit method to test the functionality of the controller where we create values for him
Same.

2022-09-17 20:40 UTC, fjlopez commented
Format the documentation properly. If you are using IntelliJ, toggle https://www.jetbrains.com/help/idea/working-with-code-documentation.html#toggle-rendered-view and you will see if the docs looks good or should be improved.

2022-09-17 23:41 UTC, HectorRute98 commented
Hello! I think that the changes in my fork have been made correctly and have been saved in this same pull request without the necessity to create a new one. 
If not, could you tell me how I should do it?.
Many thanks for your time.

2022-09-21 09:08 UTC, fjlopez approved these changes

2022-09-21 09:14 UTC, merged

2022-09-21 09:15 UTC, fjlopez commented
Done.